# Generated by Django 6.1.1 on 2026-09-04 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='HeartHandshake', max_length=50)),
                ('color_accent', models.CharField(default='#10B981', max_length=20)),
                ('sdg_alignment', models.CharField(blank=True, help_text='e.g. SDG 4: Quality Education, SDG 13: Climate Action', max_length=200)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='impact_areas/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImpactReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField(default=2026)),
                ('summary', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='reports/covers/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/pdfs/')),
                ('published_date', models.DateField(auto_now_add=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImpactStatistic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('counter_value', models.CharField(help_text='e.g. 50+, 120+, 50,000+, 2,500+', max_length=50)),
                ('raw_number', models.BigIntegerField(default=0)),
                ('suffix', models.CharField(blank=True, default='+', max_length=20)),
                ('icon_name', models.CharField(default='Award', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImpactMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metric_type', models.CharField(choices=[('REACH', 'Reach (People/Communities)'), ('PARTICIPATION', 'Participation (Volunteers/Events)'), ('OUTPUT', 'Output (Trees, Classrooms, Activities)'), ('OUTCOME', 'Outcome (Transformation/Improvement)'), ('FINANCIAL', 'Financial (Funds Deployed)')], default='OUTPUT', max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('baseline_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('target_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('achieved_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('impact_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='impact.impactarea')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
