# Generated by Django 6.1.1 on 2026-09-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_interest_userprofile_interests_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('login', 'Login'), ('reset', 'Password reset')], max_length=10),
        ),
    ]
