# Generated by Django 6.1.1 on 2026-09-04 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('partner_type', models.CharField(choices=[('CSR', 'Corporate / CSR Partner'), ('NGO', 'Non-Profit / NGO'), ('GOVERNMENT', 'Government / Municipal'), ('ACADEMIC', 'Academic / Research Institution'), ('COMMUNITY', 'Citizen / Resident Group')], default='CSR', max_length=30)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/logos/')),
                ('description', models.TextField(blank=True)),
                ('since_year', models.PositiveIntegerField(default=2024)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerEnquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('org_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('org_type', models.CharField(default='Corporate / CSR', max_length=50)),
                ('area_of_interest', models.CharField(help_text='e.g. Lake Rejuvenation, Education, Afforestation', max_length=200)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('expected_contribution', models.CharField(blank=True, help_text='Grant, CSR funds, Volunteering manpower', max_length=150)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New Lead'), ('CONTACTED', 'Contacted'), ('IN_REVIEW', 'Proposal in Review'), ('CONVERTED', 'Converted Partner'), ('CLOSED', 'Closed')], db_index=True, default='NEW', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Partner Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportedProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('contribution_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('contribution_type', models.CharField(default='CSR Grant', max_length=100)),
                ('year', models.PositiveIntegerField(default=2026)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_projects', to='partners.partner')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_supporters', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
