# Generated by Django 6.1.1 on 2026-09-04 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('impact', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Story Categories',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('beneficiary_name', models.CharField(help_text='Individual, family, or community name', max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('challenge', models.TextField(help_text='The background challenge faced by the community')),
                ('intervention', models.TextField(help_text='The action and support provided')),
                ('outcome', models.TextField(help_text='Measurable change and current situation')),
                ('quote', models.TextField(blank=True, help_text='Direct quote from beneficiary or community leader')),
                ('quote_author', models.CharField(blank=True, max_length=150)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='stories/covers/')),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='stories/before_after/')),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='stories/before_after/')),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('focus_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='impact.impactarea')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='projects.project')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='stories.storycategory')),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['-featured', '-published_date'],
            },
        ),
    ]
