# Generated by Django 6.1.1 on 2026-09-04 04:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('impact', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerOpportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('location', models.CharField(help_text='e.g. Bengaluru, Remote, On-site', max_length=200)),
                ('commitment', models.CharField(help_text='e.g. 4 hours/weekend, 10 hours/week', max_length=100)),
                ('spots_available', models.PositiveIntegerField(default=10)),
                ('spots_filled', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField()),
                ('requirements', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open for Applications'), ('FILLED', 'Filled'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20)),
                ('focus_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_opportunities', to='impact.impactarea')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_opportunities', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Volunteer Opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('skills', models.CharField(help_text='Comma-separated skills', max_length=255)),
                ('availability', models.CharField(help_text='e.g. Weekends, Weekdays, Evenings', max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Verified & Active'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20)),
                ('total_hours_contributed', models.DecimalField(decimal_places=1, default=0.0, max_digits=8)),
                ('interests', models.ManyToManyField(blank=True, related_name='volunteers', to='volunteers.volunteerinterest')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerParticipation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=1, max_digits=5)),
                ('activity_performed', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_participations', to='projects.project')),
                ('volunteer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='volunteers.volunteerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('statement_of_purpose', models.TextField()),
                ('experience', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Accepted'), ('REJECTED', 'Declined')], db_index=True, default='PENDING', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='volunteers.volunteeropportunity')),
                ('volunteer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='volunteers.volunteerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('opportunity', 'volunteer_profile')},
            },
        ),
    ]
