# Generated by Django 6.1.1 on 2026-09-27 14:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('certificate_code', models.CharField(db_index=True, help_text='Unique verifiable certificate identification number, e.g. RI-CERT-2026-XXXX', max_length=100, unique=True)),
                ('title', models.CharField(default='Certificate of Volunteer Service', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Summary of contribution or recognition')),
                ('issue_date', models.DateField()),
                ('hours_recognized', models.DecimalField(decimal_places=1, default=0.0, max_digits=6)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active & Valid'), ('REVOKED', 'Revoked')], db_index=True, default='ACTIVE', max_length=20)),
                ('issued_by', models.CharField(default='Responsible Individuals Foundation', max_length=150)),
                ('volunteer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='volunteers.volunteerprofile')),
            ],
            options={
                'verbose_name': 'Volunteer Certificate',
                'verbose_name_plural': 'Volunteer Certificates',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
    ]
