# Generated by Django 6.1.1 on 2026-09-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Accepted'), ('REJECTED', 'Declined'), ('WAITLISTED', 'Waitlisted')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
